version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: numbat-mcp
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-linux-gnu
          - CXX=zig c++ -target aarch64-linux-gnu
      - goos: darwin
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-macos-none
          - CXX=zig c++ -target aarch64-macos-none

archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
